Fix bug where tmux-sessionizer wouldn't set the correct hist_file

diff --git a/stow/tmux-sessionizer/.local/bin/tmux-sessionizer b/stow/tmux-sessionizer/.local/bin/tmux-sessionizer
--- a/stow/tmux-sessionizer/.local/bin/tmux-sessionizer
+++ b/stow/tmux-sessionizer/.local/bin/tmux-sessionizer
@@ -1,11 +1,9 @@
 #!/usr/bin/env bash
 
 set -e
+set -o pipefail
 
 declare -A sessions
-
-# NOTE: for debbuging
-declare -p > /tmp/_env_before.$$
 
 print-help() {
 	cat <<END
@@ -13,17 +11,13 @@ Usage: ${name} [OPTIONS]... <session>
 Manage tmux sessions in TMUX_SESSIONIZER_PROJECTS_DIR enviroment variable.
 
 Options:
--n, --session <session> open a new or existing session
-
---show-session-info     options: session-file, history, server-sock
-
--s, --save-session      save the current or selected session
-
--k, --kill-and-switch   kills current or selected session and switch to other one
-
---no-attach             don't attach to the new sesssion
-
+--debug                 print debug information after the execution
 -h, --help              print this help message
+-n, --session <session> open a new or existing session
+--show-session-info     options: session-file, history, server-sock
+-s, --save-session      save the current or selected session
+-k, --kill-and-switch   kills current or selected session and switch to other one
+--no-attach             don't attach to the new sesssion
 END
 }
 
@@ -36,24 +30,18 @@ is-managed() {
 		return 1
 	fi
 
-	if [ -n "$(pgrep tmux)" ]; then
-		if tmux has-session -t "$session" 2>/dev/null && ! tmux show-environment -t "$session" "TMUX_SESSIONIZER" > /dev/null 2>&1; then
-			return 1
-		fi
-	fi
-
 	return 0
 }
 
 debug-dump() {
 	local _session=$session
-	local _session_file="$HOME/.cache/$name/$_session" 
-	local _hist_file="$HOME/.cache/$name/${_session}_history" 
-	local _server_sock="/tmp/$name-$_session"
+	[ -e "$HOME/.cache/$name/$_session" ] && local _session_file="$HOME/.cache/$name/$_session.vim" 
+	[ -e "$HOME/.cache/$name/${_session}_history" ] && local _hist_file="$HOME/.cache/$name/${_session}_history" 
+	[ -e "/tmp/$name-$_session"local ] && _server_sock="/tmp/$name-$_session"
 	if [[ -n $TMUX_SESSIONIZER && -z $session ]]; then 
 		_session="$TMUX_SESSIONIZER_SESSION_NAME"
 		_session_file="$TMUX_SESSIONIZER_NVIM_SESSION_FILE"
-		_hist_file="$HOME/.cache/$name/${_session}_history" 
+		_hist_file="$HISTFILE" 
 		_server_sock="$TMUX_SESSIONIZER_NVIM_SERVER_SOCK"
 	fi
 
@@ -63,16 +51,17 @@ debug-dump() {
 		local managed=false
 	fi
 
-	echo "search dir: $TMUX_SESSIONIZER_PROJECTS_DIR"
+	echo "search dir: $search_dir"
 	echo "name:$name, managed:$managed, session:$session, kill:$kill, search:$search, save:$save, attach:$attach"
 	if [[ -n $TMUX_SESSIONIZER && "$managed" == true ]]; then
 		echo "s:$_session sf:$_session_file, srv:$_server_sock"
 	fi
 
-	declare -p > /tmp/_env_after.$$
+	echo "env:"
+	declare -p > "/tmp/tmux_sessionizer_env_after"
 	declare -- search="1"
-	comm -13 <(sort /tmp/_env_before.$$) <(sort /tmp/_env_after.$$) | sed 's/declare\s-. //'
-	rm -f /tmp/_env_before.$$ /tmp/_env_after.$$
+	comm -13 <(sort "/tmp/tmux_sessionizer_env_before") <(sort "/tmp/tmux_sessionizer_env_after")
+	rm -f "/tmp/tmux_sessionizer_env_before" "/tmp/tmux_sessionizer_env_after"
 }
 
 kill-session() {
@@ -80,26 +69,20 @@ kill-session() {
 	if [[ -n $TMUX_SESSIONIZER && -z $session ]]; then 
 		attached_session="$TMUX_SESSIONIZER_SESSION_NAME"
 	else
-		attached_session="$session"
+		attached_session="$(tmux display-message -p '#S')"
 	fi
 
-	local last_session="${session:-$(tmux list-sessions -F '#S' | grep -vF "$attached_session" | head -n1)}"
-	if [ "$(tmux ls | wc -l)" -gt 1 ]; then
-		if [ "$last_session" == "default" ]; then
-			tmux kill-server
-		fi
-
-		if [ "$attach" -eq 1 ]; then
-			tmux switch-client -t "$last_session"
-		fi
-
-		tmux kill-session -t "$attached_session"
+	local last_session="$(tmux list-sessions -F '#S' | grep -v "$attached_session\|default" | head -n1)"
+	if [ "$attach" -eq 1 ] && [ -n "$last_session" ]; then
+		tmux switch-client -t "$last_session"
 	fi
+
+	tmux kill-session -t "$attached_session"
 }
 
 save-session() {
-	local _session=$session
-	local _session_file="$HOME/.cache/$name/$_session" 
+	local _session="${session:-$(tmux display-message -p '#S')}"
+	local _session_file="$HOME/.cache/$name/$_session.vim" 
 	local _server_sock="/tmp/$name-$_session"
 	if [[ -n $TMUX_SESSIONIZER && -z $session ]]; then 
 		_session="$TMUX_SESSIONIZER_SESSION_NAME"
@@ -124,7 +107,7 @@ save-session() {
 }
 
 find-sessions() {
-	for path in $(find "$project_dir" -mindepth 1 -maxdepth 1 -type d); do
+	for path in $(find "$search_dir" -mindepth 1 -maxdepth 1 -type d); do
 		sessions[$(basename "${path/./_}")]="$path"
 	done
 
@@ -144,10 +127,10 @@ find-sessions() {
 }
 
 make-new-session() {
-	local session_file="$HOME/.cache/$name/$session"
+	local session_file="$HOME/.cache/$name/$session.vim"
 	local hist_file="$HOME/.cache/$name/${session}_history"
 	local server_sock="/tmp/$name-$session"
-	local session_path="${sessions["$session"]:-$(realpath "$project_dir/$session")}"
+	local session_path="${sessions["$session"]:-$(realpath "$search_dir/$session")}"
 
 	if [ -z "$(pgrep tmux)" ]; then
 		tmux -ds default
@@ -157,34 +140,21 @@ make-new-session() {
 		return
 	fi
 
-	if [[ $new -eq 1 ]]; then
-		if [[ ! -d "$session_path" ]]; then
-			mkdir -p "$session_path"
-		fi
-
-		if [[ -e $hist_file ]]; then
-			rm "$hist_file"
-		fi
-
-		if [[ -e $session_file ]]; then
-			rm "$session_file"
-		fi
-
-		if [ ! -e "$hist_file" ]; then
-			touch "$hist_file"
-		fi
-	fi
-
 	tmux new-session -ds $session -c "$session_path"
-	tmux set-environment -t "$session" "TMUX_SESSIONIZER" "1" 
 	tmux set-environment -t "$session" "HISTFILE" "$hist_file" 
+	tmux set-environment -t "$session" "TMUX_SESSIONIZER" "1" 
+	tmux set-environment -t "$session" "TMUX_SESSIONIZER_PROJECTS_DIR" "$search_dir" 
 	tmux set-environment -t "$session" "TMUX_SESSIONIZER_SESSION_NAME" "$session" 
 	tmux set-environment -t "$session" "TMUX_SESSIONIZER_NVIM_SESSION_FILE" "$session_file" 
 	tmux set-environment -t "$session" "TMUX_SESSIONIZER_NVIM_SERVER_SOCK" "$server_sock" 
-	tmux new-window -c "$session_path" -t "$session"
+	tmux set-hook -t "$session" after-new-window 'send-keys " HISTFILE=\"\$HISTFILE:\$(tmux display-message -p \#I_\#P)\";fc -p \$HISTFILE;clear;source \$HOME/.zshrc" C-m'
+
+	tmux new-window -t "$session:1" -c "$session_path"
 	tmux kill-window -t "$session:0"
-	tmux new-window -c "$session_path" -t "$session"
-	tmux select-window -t "$session:0"
+
+	# don't know if this is right but if we sleep the histfile gets the correct window index
+	sleep "0.5"
+	tmux new-window -t "$session:1" -c "$session_path"
 	if [ ! -e $server_sock ]; then
 		if [ -e "$session_file" ]; then
 			tmux send-keys -t "$session:1" "nvim --listen '$server_sock' -S '$session_file'" C-m
@@ -194,23 +164,45 @@ make-new-session() {
 	fi
 }
 
+make-session-files() {
+	local session_path="${sessions["$session"]:-$(realpath "$search_dir/$session")}"
+	if [ ! -d "$session_path" ]; then
+		mkdir -p "$session_path"
+	fi
+
+	local hist_file="$HOME/.cache/$name/${session}_history"
+	for f in "$hist_file"*; do
+		[ -e "$f" ] || continue
+		rm -- "$f"
+	done
+
+	local session_file="$HOME/.cache/$name/$session.vim"
+	if [ -e "$session_file" ]; then
+		rm "$session_file"
+	fi
+}
+
 show-session-info() {
-	local _session=$session
-	local _session_file="$HOME/.cache/$name/$_session" 
+	local _session="$session"
+	local _session_file="$HOME/.cache/$name/$_session.vim" 
 	local _hist_file="$HOME/.cache/$name/${_session}_history" 
 	local _server_sock="/tmp/$name-$_session"
 	if [[ -n $TMUX_SESSIONIZER && -z $session ]]; then 
 		_session="$TMUX_SESSIONIZER_SESSION_NAME"
 		_session_file="$TMUX_SESSIONIZER_NVIM_SESSION_FILE"
-		_hist_file="$HOME/.cache/$name/${_session}_history" 
 		_server_sock="$TMUX_SESSIONIZER_NVIM_SERVER_SOCK"
 	fi
+
+	if [ -z "$_session" ]; then
+		echo "$name: no session provided"
+		return
+	fi
+
 
 	if ! is-managed "$_session"; then
 		echo "$name: cannot show info of non-managed session"
 		return
 	fi
-
 
 	if [ -z "$_session" ]; then
 		return
@@ -223,9 +215,7 @@ show-session-info() {
 			fi
 			;;
 		history)
-			if [ -e "${_hist_file}" ]; then
-				echo $_hist_file
-			fi
+			find "$(dirname "$_hist_file")" -iwholename "$_hist_file*" | sort
 			;;
 		server-sock)
 			if [ -e "${_server_sock}" ]; then
@@ -238,19 +228,32 @@ show-session-info() {
 	esac
 }
 
+# NOTE: for debbuging
+pos=1
+for arg in "$@"; do
+	if [ "$arg" == "--debug" ]; then
+		declare -p > "/tmp/tmux_sessionizer_env_before"
+		unset pos
+		unset arg
+		trap debug-dump EXIT
+		break
+	fi
+	pos=$((pos+1))
+done
+
 name=$(basename "$0")
-project_dir=${TMUX_SESSIONIZER_PROJECTS_DIR:-$HOME/code}
+search_dir=${TMUX_SESSIONIZER_PROJECTS_DIR:-"$HOME/code"}
 
 search=1
 attach=1
 help=0
-debug_dump=0
 save=0
 kill=0
 show=0
 show_cmd=""
 arg=0
-while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do 
+new=0
+while [[ $# -ge 1 ]]; do 
 	case $1 in
 		-h|--help)
 			help=1
@@ -259,6 +262,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
 		-n|--session)
 			shift
 			search=0
+			new=1
 			session=$1
 			;;
 		-k|--kill-and-switch)
@@ -268,11 +272,10 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
 			attach=0
 			;;
 		-s|--save-session)
-			search=0
 			save=1
 			;;
-		--debug-dump)
-			debug_dump=1
+		--debug)
+			debug=1
 			;;
 		--show-session-info)
 			shift
@@ -281,25 +284,28 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
 				session-file|history|server-sock)
 					show_cmd=$1
 					;;
+
+				'')
+					echo "$name: options: session-file|history|server-sock"
+					exit 1
+					;;
 				*)
 					echo "$name: invalid option '$1'"
 					exit 1
 			esac
 			;;
 		*)
-			echo "$name: unknown flag $1"
-			exit 1
+			if [ -z $session ]; then
+				search=0
+				session=$(tr '.' '_' <<< "$1")
+			else
+				echo "$name: unknown flag '$1'"
+				exit 1
+			fi
 			;;
 	esac
 	shift
 done
-
-if [ $# -eq 1 ]; then
-	search=0
-	arg=1
-	session=$(tr '.' '_' <<< "$1")
-	shift
-fi
 
 if grep -q "/" <<< "$session"; then
 	echo "$name: invalid session name '$session'"
@@ -311,20 +317,16 @@ if [ "$help" -eq 1 ]; then
 	exit 0
 fi
 
-if [ ! -d "$project_dir" ]; then
-	echo "$name: missing ~/code or invalid path in TMUX_SESSIONIZER_PROJECTS_DIR"
+if [ ! -d "$search_dir" ]; then
+	echo "$name: invalid path '$search_dir' in TMUX_SESSIONIZER_PROJECTS_DIR"
 	exit 1
 fi
 
 find-sessions
 
-if [ "$debug_dump" -eq 1 ]; then
-	debug-dump
-	exit 0
-fi
-
 if [ "$show" -eq 1 ]; then
 	show-session-info
+	exit $?
 fi
 
 if [ "$kill" -eq 1 ] && [ "$save" -eq 1 ]; then
@@ -347,7 +349,7 @@ if [ $search -eq 1 ]; then
 	if [ -n "$TMUX_SESSIONIZER" ]; then
 		session=$(
 			printf "%s\n" "${!sessions[@]}"                                                                                                     |
-			awk '!/^\[TMUX\]/{tmux[++n]=$0; next} !/\[TMUX\] '$TMUX_SESSIONIZER_SESSION_NAME'/ {print $0} END{for(i=1;i<=n;i++) print tmux[i]}' |
+			awk '!/^\[TMUX\]/{tmux[++n]=$0; next} !/\[TMUX\] '$search_dir'/ {print $0} END{for(i=1;i<=n;i++) print tmux[i]}' |
 			fzf                                                                                                                                 |
 			sed 's/\[TMUX\] //'
 			)
@@ -362,19 +364,19 @@ if [ $search -eq 1 ]; then
 fi
 
 if [ -z $session ]; then
+	echo "$name: no session selected"
 	exit 0
 fi
 
-if is-managed "$session" && [ "$search" -eq 1 ]; then
-	new=0
-elif ! is-managed "$session" && [ "$arg" -eq 0 ]; then
-	new=1
+if is-managed "$session"; then
+	make-new-session
+elif ! is-managed "$session" && [[ "$new" -eq 1 ]]; then
+	make-session-files
+	make-new-session
 else
 	echo "$name: cannot open session '$session'"
-	exit 0
+	exit 1
 fi
-
-make-new-session
 
 if [ "$attach" -eq 1 ]; then
 	if [ -z "$TMUX" ]; then
